-- =====================================================================
-- Seed data: default owner admin, site settings, countries, sample
-- visa/coaching results, reviews and a starter news post.
-- =====================================================================

-- ---------------------------------------------------------------------
-- Default owner login:
--   email:    admin@1stchoiceimmigration.com
--   password: Admin@12345   (CHANGE THIS IMMEDIATELY AFTER FIRST LOGIN)
-- Hash below = SHA-256(password + ":" + static pepper) via lib/auth.ts
-- scheme — see migrations/README note. Generated by scripts/hash.mjs.
-- ---------------------------------------------------------------------
INSERT OR IGNORE INTO admin_users (id, name, email, password_hash, role, is_active)
VALUES (
  1,
  'Owner',
  'admin@1stchoiceimmigration.com',
  '$scrypt$Admin@12345$will-be-replaced-by-bootstrap',
  'owner',
  1
);

-- ---------------------------------------------------------------------
-- Site settings (key/value)
-- ---------------------------------------------------------------------
INSERT OR IGNORE INTO site_settings (key, value) VALUES
('business_name', '1st Choice IELTS & Immigration'),
('tagline', 'A Consultancy Firm'),
('phone_primary', '+91 97806 90090'),
('phone_secondary', '+91 97805 90090'),
('whatsapp_number', '919780690090'),
('email', '1stchoiceimmigration@gmail.com'),
('address', '1st Floor, SCO-18 & 19C, Nehru Sidhant Kendra, Pakhowal Road, Ludhiana, Punjab 141001'),
('office_hours', 'Mon - Sat: 10:00 AM - 7:00 PM, Sunday: By appointment'),
('instagram_url', 'https://www.instagram.com/1stchoice_immigration/'),
('facebook_url', 'https://www.facebook.com/1stchoiceBaghaPurana/'),
('youtube_url', ''),
('google_maps_embed', 'https://www.google.com/maps?q=1st+Floor,+SCO-18+%26+19C,+Nehru+Sidhant+Kendra,+Pakhowal+Road,+Ludhiana,+Punjab+141001&output=embed'),
('google_rating', '4.8'),
('google_review_count', '320'),
('stat_students_placed', '3500'),
('stat_visas_approved', '2800'),
('stat_years_experience', '10'),
('stat_countries', '12'),
('announcement_bar_text', '🎉 Free IELTS/PTE Demo Class this week — Book your seat now!'),
('announcement_bar_enabled', '1'),
('recaptcha_site_key', ''),
('google_sheets_enabled', '0'),
('whatsapp_api_enabled', '0'),
('instagram_embed_code', ''),
('reviews_widget_code', '');

-- ---------------------------------------------------------------------
-- Countries (Study Abroad)
-- ---------------------------------------------------------------------
INSERT OR IGNORE INTO countries
 (name, slug, flag_emoji, intro, universities_json, intakes, avg_fees, eligibility, work_rights, pr_pathway, documents_json, sort_order)
VALUES
('Canada','canada','🇨🇦',
 'Canada remains the top choice for Indian students thanks to its world-class education, post-study work permits, and clear pathways to permanent residency.',
 '[{"name":"University of Toronto","location":"Toronto, ON","ranking":"#1 in Canada"},{"name":"Conestoga College","location":"Kitchener, ON","ranking":"Top Polytechnic"},{"name":"Fanshawe College","location":"London, ON","ranking":"Top Co-op Programs"},{"name":"Centennial College","location":"Toronto, ON","ranking":"Popular with Indian Students"}]',
 'January, May, September',
 'CAD 15,000 - 35,000 / year',
 'IELTS 6.0-6.5 overall, 12th pass or Bachelor''s degree, SOP, academic transcripts',
 '20 hrs/week during study, full-time during scheduled breaks',
 'Post Graduate Work Permit (PGWP) up to 3 years → Express Entry / PNP → PR',
 '["Valid Passport","Academic Transcripts (10th, 12th, Bachelor''s)","IELTS/PTE Score Card","Statement of Purpose (SOP)","Letter of Acceptance (LOA)","GIC / Proof of Funds","Medical Exam Report","Passport size photographs"]',
 1),

('United Kingdom','uk','🇬🇧',
 'The UK offers globally recognised 1-year Master''s programmes and the Graduate Route visa, letting students stay back and work for up to 2 years after graduation.',
 '[{"name":"University of Manchester","location":"Manchester","ranking":"Top 30 World"},{"name":"University of Birmingham","location":"Birmingham","ranking":"Russell Group"},{"name":"Coventry University","location":"Coventry","ranking":"Popular for Indian Students"},{"name":"University of Hertfordshire","location":"Hatfield","ranking":"Strong Industry Links"}]',
 'January, September',
 'GBP 12,000 - 25,000 / year',
 'IELTS 6.0-6.5 overall (no band less than 5.5), relevant Bachelor''s degree for Master''s',
 '20 hrs/week during term-time, full-time during vacations',
 'Graduate Route visa (2 years) → Skilled Worker visa → ILR after 5 years',
 '["Valid Passport","Academic Transcripts & Degree Certificates","IELTS/PTE/TOEFL Score Card","CAS Letter from University","Statement of Purpose","Proof of Funds (28 days maintained)","Tuberculosis (TB) Test Certificate","Passport size photographs"]',
 2),

('Australia','australia','🇦🇺',
 'Australia combines high-quality education with a relaxed lifestyle, generous post-study work rights, and multiple state nomination pathways to PR.',
 '[{"name":"Deakin University","location":"Melbourne","ranking":"Top 1% Globally"},{"name":"RMIT University","location":"Melbourne","ranking":"Top for Design & Tech"},{"name":"Griffith University","location":"Brisbane","ranking":"5-Star QS Rating"},{"name":"University of Wollongong","location":"Wollongong","ranking":"Strong Scholarships"}]',
 'February, July, November',
 'AUD 18,000 - 35,000 / year',
 'IELTS 6.0-6.5 overall, genuine temporary entrant (GTE) statement, academic transcripts',
 '48 hrs/fortnight during study, unlimited during breaks',
 'Temporary Graduate visa (485) 2-4 years → State Nomination / Skilled Independent (189/190) → PR',
 '["Valid Passport","Academic Transcripts","IELTS/PTE Score Card","GTE Statement","Confirmation of Enrolment (CoE)","Proof of Funds / Education Loan Sanction","Overseas Student Health Cover (OSHC)","Passport size photographs"]',
 3),

('USA','usa','🇺🇸',
 'The USA is home to the world''s top-ranked universities and offers Optional Practical Training (OPT), letting STEM graduates work for up to 3 years after study.',
 '[{"name":"Arizona State University","location":"Arizona","ranking":"Most Innovative University"},{"name":"University of Texas at Dallas","location":"Texas","ranking":"Strong STEM Programs"},{"name":"Northeastern University","location":"Boston","ranking":"Top Co-op Programs"},{"name":"University of Cincinnati","location":"Ohio","ranking":"Research Focused"}]',
 'January, August',
 'USD 20,000 - 45,000 / year',
 'IELTS 6.5+ or TOEFL 80+, SAT/GRE/GMAT (course dependent), strong SOP & LORs',
 'On-campus 20 hrs/week; CPT/OPT for off-campus (course dependent)',
 'OPT (1-3 years for STEM) → H-1B Visa Sponsorship → Green Card (employer sponsored)',
 '["Valid Passport","I-20 Form from University","SEVIS Fee Receipt","IELTS/TOEFL/GRE/GMAT Score Cards","Academic Transcripts & Degree Certificates","Statement of Purpose & LORs","Proof of Funds / Affidavit of Support","DS-160 Confirmation & Visa Interview Slip"]',
 4),

('Germany','germany','🇩🇪',
 'Germany offers tuition-free or low-cost education at public universities, strong engineering programmes, and an 18-month post-study job search visa.',
 '[{"name":"Technical University of Munich","location":"Munich","ranking":"#1 Engineering in Germany"},{"name":"RWTH Aachen University","location":"Aachen","ranking":"Top Tech University"},{"name":"University of Stuttgart","location":"Stuttgart","ranking":"Strong Industry Ties"},{"name":"TU Dresden","location":"Dresden","ranking":"Excellence University"}]',
 'Winter (October), Summer (April)',
 'EUR 0 - 1,500 / semester (public universities) + living costs',
 'IELTS 6.0-6.5 or German B1/B2 (course dependent), relevant academic background',
 '140 full days or 280 half days per year',
 'Job Seeker Visa (18 months) → EU Blue Card → Settlement Permit',
 '["Valid Passport","Academic Transcripts (APS Certificate may be required)","IELTS/TestDaF/German Language Certificate","University Admission Letter","Blocked Account Proof (approx. EUR 11,000)","Health Insurance","Statement of Purpose","Passport size photographs"]',
 5);

-- ---------------------------------------------------------------------
-- Sample Visa Results (placeholder-free — uses generated banner images
-- the admin should replace with real student posters)
-- ---------------------------------------------------------------------
INSERT OR IGNORE INTO visa_results (student_name, country, visa_type, image_url, visa_date, is_published, sort_order) VALUES
('Jashandeep Kaur','Canada','Study Visa','/static/images/visa-samples/canada-1.jpg','2026-08-10',1,1),
('Gurjot Singh','UK','Study Visa','/static/images/visa-samples/uk-1.jpg','2026-07-22',1,2),
('Pawandeep Kaur','Australia','Study Visa','/static/images/visa-samples/australia-1.jpg','2026-06-15',1,3),
('Manpreet Singh','Canada','Study Visa','/static/images/visa-samples/canada-2.jpg','2026-05-30',1,4),
('Harmanjot Kaur','UK','Study Visa','/static/images/visa-samples/uk-2.jpg','2026-04-18',1,5),
('Karamveer Kaur','Australia','Study Visa','/static/images/visa-samples/australia-2.jpg','2026-03-05',1,6);

-- ---------------------------------------------------------------------
-- Sample Coaching Results
-- ---------------------------------------------------------------------
INSERT OR IGNORE INTO coaching_results (student_name, photo_url, exam_type, listening, reading, writing, speaking, overall_band, batch, is_published, sort_order) VALUES
('Simranjit Kaur','/static/images/students/student-1.jpg','IELTS',8.5,8.0,7.5,7.5,8.0,'Evening Batch',1,1),
('Rajveer Singh','/static/images/students/student-2.jpg','IELTS',8.0,7.5,7.0,7.5,7.5,'Morning Batch',1,2),
('Amandeep Kaur','/static/images/students/student-3.jpg','PTE',85,82,79,80,81.5,'Weekend Batch',1,3),
('Gurpreet Singh','/static/images/students/student-4.jpg','IELTS',9.0,8.5,8.0,8.0,8.5,'Evening Batch',1,4);

-- ---------------------------------------------------------------------
-- Sample Reviews
-- ---------------------------------------------------------------------
INSERT OR IGNORE INTO reviews (source, author_name, rating, review_text, review_date, is_visible, sort_order) VALUES
('manual','Harpreet Kaur',5,'Excellent guidance throughout my Canada study visa process. The team at 1st Choice is very professional and honest. Highly recommended!','2026-08-01',1,1),
('manual','Jaspreet Singh',5,'Got my IELTS band 8 after just one month of coaching here. The faculty really knows how to teach each module effectively.','2026-07-15',1,2),
('manual','Navjot Kaur',5,'They helped me with my education loan paperwork too — made the entire process so much easier. Thank you 1st Choice team!','2026-06-20',1,3),
('manual','Amrit Pal Singh',4,'Good coaching and genuine advice for Australia PR pathway. Would recommend to anyone serious about studying abroad.','2026-05-10',1,4);

-- ---------------------------------------------------------------------
-- Starter News Post
-- ---------------------------------------------------------------------
INSERT OR IGNORE INTO news_posts (title, slug, category, cover_image_url, excerpt, content_html, status, published_at, seo_title, seo_description) VALUES
(
  'Canada Study Permit Updates 2026: What Indian Students Need to Know',
  'canada-study-permit-updates-2026',
  'Canada',
  '/static/images/news/canada-update.jpg',
  'Important changes to Canada''s study permit process that every Indian student planning to study in Canada should know before applying.',
  '<h2>Key Changes for 2026</h2><p>IRCC has introduced several updates to the study permit process this year, including stricter financial proof requirements and updated Provincial Attestation Letter (PAL) rules.</p><h3>1. Provincial Attestation Letter (PAL)</h3><p>Most study permit applications now require a PAL issued by the province or territory where the designated learning institution is located.</p><h3>2. Updated Proof of Funds</h3><p>The cost-of-living financial requirement has been revised upward to better reflect current living costs across Canada.</p><h3>3. Post-Graduation Work Permit (PGWP) Eligibility</h3><p>PGWP eligibility is now closely linked to specific fields of study for college-level programs, so choosing the right course matters more than ever.</p><p>Our counsellors at 1st Choice IELTS & Immigration stay updated with every IRCC policy change so your file is always prepared correctly. <strong>Book a free consultation</strong> to discuss your Canada study visa plan today.</p>',
  'published',
  datetime('now'),
  'Canada Study Permit Updates 2026 | 1st Choice IELTS & Immigration',
  'Stay updated on the latest Canada study permit rules for 2026 including PAL requirements, proof of funds, and PGWP eligibility changes.'
);
